server:
  port: 8877 
# spring boot jpa related properties  
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3388/kprules?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: kprules
    password: password
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
# graphql related properties
graphql:
  servlet:
    corsEnabled: true
    mapping: /graphql
    enabled: true
graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true
  cdn:
    enabled: false
    version: 0.11.11