spring:
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3388/kprules?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: kprules
    password: password
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE


